### PR TITLE
WIN_SYMBOLS hash fix & update

### PR DESCRIPTION
**Pull request by krage**
### Describe the change
Updates the WIN_SYMBOLS hash fixing the unescaped `:rsquo` and `:lsquo` single quotes (referenced in #14) and replacing the symbols used with nicer options available in default Windows fonts.  The vast majority of the symbols present in the regular SYMBOLS table were copied over directly.  Of that set the following were missing in typical fonts as displayed in standard Windows command prompt:

- Consolas missing: `:diamond`
- Courier New missing: `:bar`, `:diamond`
- Raster Fonts missing: `:bar`, `:diamond`, `:bullet`

For these 3 missing characters I swapped in representative alternatives that displayed correctly in these basic fonts.

### Benefits
Output will be nicer and more consistent across platforms.

### Drawbacks
It's possible older versions of Windows include less complete versions of these default fonts that may lack some of these symbols resulting in display issues.

### Requirements
Put an X between brackets on each line if you have done the item:
[] Tests written & passing locally?
[] Code style checked?
[] Rebased with `master` branch?
[] Documentation updated?

### CODE REVIEW

**Comment by krage** [comment]
Beyond the fix for the unescaped quotes a good alternative to the rest of the symbols changes made here would be maintaining the WIN_SYMBOLS hash as a plain ASCII compatibility set that was only enabled via an opt-in option rather than automatically forced by platform detection.

**Comment by piotrmurach** [comment]
I would probably stick to fixing the two symbols in this PR. I see little value in updating all the `WIN_SYMBOLS` to match `SYMBOLS`. At best this is duplicating what is already there. I like your idea of renaming `WIN_SYMBOLS` to `ASCII_SYMBOLS` as a compatibility feature and providing an option to configure this. I think it is key to remember that not everybody is on the latest and greatest system. However, having unicode symbols as default sounds appealing. I would even go so far as allowing users to overwrite any default symbols anyhow using `:symbols` option. For example

```ruby
symbols: :ascii # => this gets the ascii default symbols
symbols: :ascii, { laquo: '<<<' } # => this gets the ascii symbols and overrides one symbol
```

**Comment by krage** [comment]
OK sounds reasonable.  The first commit in this PR is only the single quotes fixes, perhaps just cherry pick that one for now?

**Comment by krage** [comment]
Closing in favor of #18

**Pull request closed without merging**
